name: tesla
description: "Control and monitor Tesla Products"
version: 0.1.2
homepage: "https://github.com/SpinlockLabs/tesla.dart"
authors:
- "Kenneth Endfinger <kaendfinger@gmail.com>"
- "Rody Davis Jr <rody.davis.jr@gmail.com>"
environment:
  sdk: ">=2.0.0 <3.0.0"
